#!/usr/bin/env python3

import argparse
from json import loads
from requests import get

API_KEY = 'AIzaSyDSyFnKwdgjR-t4UiB7_R91BRYxUoKXK3s'
BASE_URL = 'https://www.googleapis.com/youtube/v3/search\
?part=snippet&type=video'

def main(query, result_count):
    query_string = '+'.join(query)
    search_query = get(BASE_URL + '&q=' + query_string + '&key=' + API_KEY)
    result = loads(search_query.text)['items']
    for i in range(0, result_count):
        print(result[i]['snippet']['title'] + ':')
        print('https://www.youtube.com/watch?v=' + result[i]['id']['videoId'])
        if not i == result_count - 1:
            print()

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('query', nargs='+',
        help='one or more arguments to search youtube')
    parser.add_argument('-n', '--result_count', nargs='?',
        help='number of results (default: 3; max: 5)',
        default=3, type=int, choices=range(1, 6))
    args = parser.parse_args()
    main(args.query, args.result_count)
